### ISSUE TITLE
Running composer update throws errors about patches not applied

### ISSUE THREAD

**Issue by cnovak** [micovery/apigee-drupal8-dev-portal#1]
If you try to run `composer update` on the main composer file in `/drupal/projects` to update dependencies, you will see the patches on the project fail:

<img width="1073" alt="patches-fail" src="https://user-images.githubusercontent.com/613093/75491863-7a830100-596b-11ea-9801-d9aef886fc7e.png">

**Comment by micovery** [comment]
Thanks for reporting, and fixing this. I've rebuilt the image and pushed it to dockerhub.
